import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Orbitron } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Nav from "./components/Nav";

const orbitron = Orbitron({
  variable: "--font-Orbitron",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body className={orbitron.className}>
        <Provider><Nav></Nav>{children}</Provider>
      </body>
    </html>
  );
}
